[2024-10-09T11:49:57.345+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T11:49:57.437+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio.consume_and_store_to_minio_in_batches scheduled__2024-10-09T10:00:00+00:00 [queued]>
[2024-10-09T11:49:57.498+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio.consume_and_store_to_minio_in_batches scheduled__2024-10-09T10:00:00+00:00 [queued]>
[2024-10-09T11:49:57.501+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-09T11:49:57.564+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): consume_and_store_to_minio_in_batches> on 2024-10-09 10:00:00+00:00
[2024-10-09T11:49:57.590+0000] {standard_task_runner.py:72} INFO - Started process 7783 to run task
[2024-10-09T11:49:57.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio', 'consume_and_store_to_minio_in_batches', 'scheduled__2024-10-09T10:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_minio.py', '--cfg-path', '/tmp/tmpe2lxhnfe']
[2024-10-09T11:49:57.648+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask consume_and_store_to_minio_in_batches
[2024-10-09T11:49:58.103+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio.consume_and_store_to_minio_in_batches scheduled__2024-10-09T10:00:00+00:00 [running]> on host 2a293f7fa826
[2024-10-09T11:49:58.992+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio' AIRFLOW_CTX_TASK_ID='consume_and_store_to_minio_in_batches' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T10:00:00+00:00'
[2024-10-09T11:49:58.995+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T11:49:59.054+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2024-10-09T11:49:59.076+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-09T11:49:59.086+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Connection complete.
[2024-10-09T11:49:59.509+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-10-09T11:49:59.512+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-10-09T11:49:59.525+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('stock_data',)
[2024-10-09T11:50:04.316+0000] {cluster.py:371} INFO - Group coordinator for my-group is ('coordinator-0', 'my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal', 9092, None)
[2024-10-09T11:50:04.319+0000] {base.py:693} INFO - Discovered coordinator coordinator-0 for group my-group
[2024-10-09T11:50:04.320+0000] {base.py:741} INFO - Starting new heartbeat thread
[2024-10-09T11:50:04.322+0000] {consumer.py:348} INFO - Revoking previously assigned partitions () for group my-group
[2024-10-09T11:50:04.328+0000] {conn.py:380} INFO - <BrokerConnection node_id=coordinator-0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: connecting to my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 [('10.0.0.2', 9092) IPv4]
[2024-10-09T11:50:04.330+0000] {conn.py:410} INFO - <BrokerConnection node_id=coordinator-0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: Connection complete.
[2024-10-09T11:50:04.330+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connected> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. 
[2024-10-09T11:50:04.431+0000] {base.py:450} INFO - (Re-)joining group my-group
[2024-10-09T11:50:04.513+0000] {base.py:521} INFO - Elected group leader -- performing partition assignments using range
[2024-10-09T11:50:04.524+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: connecting to my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 [('10.0.0.2', 9092) IPv4]
[2024-10-09T11:50:04.527+0000] {conn.py:410} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: Connection complete.
[2024-10-09T11:50:04.780+0000] {base.py:335} INFO - Successfully joined group my-group with generation 1
[2024-10-09T11:50:04.783+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('stock_data', 0)]
[2024-10-09T11:50:04.784+0000] {consumer.py:245} INFO - Setting newly assigned partitions (('stock_data', 0),) for group my-group
[2024-10-10T11:20:46.484+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T11:20:46.502+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: kafka_to_minio.consume_and_store_to_minio_in_batches scheduled__2024-10-09T10:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-10-10T11:20:46.510+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: kafka_to_minio.consume_and_store_to_minio_in_batches scheduled__2024-10-09T10:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-10-10T11:20:46.512+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-10-14T02:28:45.322+0000] {client_async.py:698} WARNING - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connected> [IPv4 ('10.0.0.2', 9092)]> timed out after 305000 ms. Closing connection.
[2024-10-14T02:28:45.323+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connected> [IPv4 ('10.0.0.2', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 305000 ms
[2024-10-14T02:28:45.350+0000] {future.py:79} ERROR - Fetch to node 0 failed: [Error 7] RequestTimedOutError: Request timed out after 305000 ms
[2024-10-14T02:28:45.359+0000] {client_async.py:952} INFO - Closing idle connection coordinator-0, last active 265309779 ms ago
[2024-10-14T02:28:45.378+0000] {conn.py:919} INFO - <BrokerConnection node_id=coordinator-0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connected> [IPv4 ('10.0.0.2', 9092)]>: Closing connection. 
[2024-10-14T02:28:45.410+0000] {conn.py:380} INFO - <BrokerConnection node_id=coordinator-0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: connecting to my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 [('10.0.0.2', 9092) IPv4]
[2024-10-14T02:28:45.411+0000] {conn.py:410} INFO - <BrokerConnection node_id=coordinator-0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: Connection complete.
[2024-10-14T02:28:45.449+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: connecting to my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 [('10.0.0.2', 9092) IPv4]
[2024-10-14T02:28:45.458+0000] {conn.py:410} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: Connection complete.
[2024-10-14T02:28:45.471+0000] {base.py:985} WARNING - Heartbeat session expired, marking coordinator dead
[2024-10-14T02:28:45.471+0000] {base.py:715} WARNING - Marking the coordinator dead (node coordinator-0) for group my-group: Heartbeat session expired.
[2024-10-14T02:28:45.486+0000] {consumer.py:794} WARNING - Auto offset commit failed for group my-group: NodeNotReadyError: coordinator-0
[2024-10-14T02:28:45.573+0000] {cluster.py:371} INFO - Group coordinator for my-group is ('coordinator-0', 'my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal', 9092, None)
[2024-10-14T02:28:45.574+0000] {base.py:693} INFO - Discovered coordinator coordinator-0 for group my-group
[2024-10-14T02:28:45.767+0000] {job.py:229} INFO - Heartbeat recovered after 265309.25 seconds
[2024-10-14T02:28:48.586+0000] {base.py:839} WARNING - Heartbeat: local member_id was not recognized; this consumer needs to re-join
[2024-10-14T02:28:48.599+0000] {consumer.py:539} ERROR - Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/coordinator/consumer.py", line 528, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/coordinator/consumer.py", line 521, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
            
[2024-10-14T02:28:48.615+0000] {consumer.py:348} INFO - Revoking previously assigned partitions (('stock_data', 0),) for group my-group
[2024-10-14T02:28:48.615+0000] {base.py:450} INFO - (Re-)joining group my-group
[2024-10-14T02:28:48.658+0000] {base.py:521} INFO - Elected group leader -- performing partition assignments using range
[2024-10-14T02:28:48.686+0000] {base.py:335} INFO - Successfully joined group my-group with generation 3
[2024-10-14T02:28:48.687+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('stock_data', 0)]
[2024-10-14T02:28:48.688+0000] {consumer.py:245} INFO - Setting newly assigned partitions (('stock_data', 0),) for group my-group
